import type { PowerUp } from "@/lib/types";

const SI = "https://cdn.simpleicons.org";
const GF = "https://www.google.com/s2/favicons?sz=128&domain=";

export const powerUps: PowerUp[] = [
  // ── Financial (7) ──────────────────────────────────────
  {
    id: "plaid",
    name: "Plaid",
    description: "Connect 12,000+ financial institutions in one click",
    category: "financial",
    logoUrl: `${GF}plaid.com`,
    connected: false,
    savingsWeight: 5,
  },
  {
    id: "chase",
    name: "Chase",
    description: "Personal and business banking, credit cards",
    category: "financial",
    logoUrl: `${SI}/chase/117ACA`,
    connected: false,
    savingsWeight: 4,
  },
  {
    id: "boa",
    name: "Bank of America",
    description: "Checking, savings, and investment accounts",
    category: "financial",
    logoUrl: `${SI}/bankofamerica/E31837`,
    connected: false,
    savingsWeight: 4,
  },
  {
    id: "wells-fargo",
    name: "Wells Fargo",
    description: "Banking and financial services",
    category: "financial",
    logoUrl: `${SI}/wellsfargo/CD1409`,
    connected: false,
    savingsWeight: 3,
  },
  {
    id: "fidelity",
    name: "Fidelity",
    description: "Brokerage and retirement accounts",
    category: "financial",
    logoUrl: `${GF}fidelity.com`,
    connected: false,
    savingsWeight: 4,
  },
  {
    id: "robinhood",
    name: "Robinhood",
    description: "Commission-free stock and crypto trading",
    category: "financial",
    logoUrl: `${SI}/robinhood/00C805`,
    connected: false,
    savingsWeight: 2,
  },
  {
    id: "capital-one",
    name: "Capital One",
    description: "Banking, credit cards, and auto loans",
    category: "financial",
    logoUrl: `${GF}www.capitalone.com`,
    connected: false,
    savingsWeight: 3,
  },

  // ── Accounting (5) ─────────────────────────────────────
  {
    id: "quickbooks",
    name: "QuickBooks",
    description: "P&L, balance sheet, chart of accounts, invoices",
    category: "accounting",
    logoUrl: `${SI}/quickbooks/2CA01C`,
    connected: false,
    savingsWeight: 5,
  },
  {
    id: "xero",
    name: "Xero",
    description: "Cloud accounting for small businesses",
    category: "accounting",
    logoUrl: `${SI}/xero/13B5EA`,
    connected: false,
    savingsWeight: 4,
  },
  {
    id: "freshbooks",
    name: "FreshBooks",
    description: "Invoicing, expenses, and time tracking",
    category: "accounting",
    logoUrl: `${GF}freshbooks.com`,
    connected: false,
    savingsWeight: 3,
  },
  {
    id: "wave",
    name: "Wave",
    description: "Free accounting and invoicing for small businesses",
    category: "accounting",
    logoUrl: `${GF}waveapps.com`,
    connected: false,
    savingsWeight: 2,
  },
  {
    id: "sage",
    name: "Sage",
    description: "Enterprise accounting and financial management",
    category: "accounting",
    logoUrl: `${SI}/sage/00DC82`,
    connected: false,
    savingsWeight: 3,
  },

  // ── Crypto (4) ─────────────────────────────────────────
  {
    id: "coinbase",
    name: "Coinbase",
    description: "Crypto exchange — holdings and transaction history",
    category: "crypto",
    logoUrl: `${SI}/coinbase/0052FF`,
    connected: false,
    savingsWeight: 4,
  },
  {
    id: "kraken",
    name: "Kraken",
    description: "Cryptocurrency exchange for loss harvesting",
    category: "crypto",
    logoUrl: `${GF}kraken.com`,
    connected: false,
    savingsWeight: 3,
  },
  {
    id: "gemini",
    name: "Gemini",
    description: "Regulated crypto exchange and custody",
    category: "crypto",
    logoUrl: `${GF}gemini.com`,
    connected: false,
    savingsWeight: 3,
  },
  {
    id: "binance-us",
    name: "Binance.US",
    description: "US-based crypto exchange",
    category: "crypto",
    logoUrl: `${SI}/binance/F0B90B`,
    connected: false,
    savingsWeight: 2,
  },

  // ── Real Estate (3) ────────────────────────────────────
  {
    id: "zillow",
    name: "Zillow",
    description: "Property values and fair market estimates",
    category: "real-estate",
    logoUrl: `${SI}/zillow/006AFF`,
    connected: false,
    savingsWeight: 3,
  },
  {
    id: "redfin",
    name: "Redfin",
    description: "Real estate data and property valuations",
    category: "real-estate",
    logoUrl: `${GF}redfin.com`,
    connected: false,
    savingsWeight: 3,
  },
  {
    id: "costar",
    name: "CoStar",
    description: "Commercial real estate data for cost segregation",
    category: "real-estate",
    logoUrl: `${GF}costar.com`,
    connected: false,
    savingsWeight: 4,
  },

  // ── Payroll (4) ────────────────────────────────────────
  {
    id: "adp",
    name: "ADP",
    description: "W-2 data, wages, FICA, contractor payments",
    category: "payroll",
    logoUrl: `${SI}/adp/D0271D`,
    connected: false,
    savingsWeight: 5,
  },
  {
    id: "gusto",
    name: "Gusto",
    description: "Payroll, employee classifications, 1099 data",
    category: "payroll",
    logoUrl: `${SI}/gusto/F45D22`,
    connected: false,
    savingsWeight: 4,
  },
  {
    id: "paychex",
    name: "Paychex",
    description: "Payroll summaries and tax deposits",
    category: "payroll",
    logoUrl: `${SI}/paychex/004B87`,
    connected: false,
    savingsWeight: 3,
  },
  {
    id: "rippling",
    name: "Rippling",
    description: "Unified payroll and HR platform",
    category: "payroll",
    logoUrl: `${GF}rippling.com`,
    connected: false,
    savingsWeight: 3,
  },

  // ── R&D (5) ─────────────────────────────────────────────
  {
    id: "jira",
    name: "Jira",
    description: "Sprint data and engineering hours for R&D credits",
    category: "r-and-d",
    logoUrl: `${SI}/jira/0052CC`,
    connected: false,
    savingsWeight: 4,
  },
  {
    id: "github",
    name: "GitHub",
    description: "Commit history and PR activity for R&D evidence",
    category: "r-and-d",
    logoUrl: `${SI}/github/181717`,
    connected: false,
    savingsWeight: 4,
  },
  {
    id: "gitlab",
    name: "GitLab",
    description: "CI/CD pipelines and merge request data for R&D documentation",
    category: "r-and-d",
    logoUrl: `${SI}/gitlab/FC6D26`,
    connected: false,
    savingsWeight: 3,
  },
  {
    id: "slack",
    name: "Slack",
    description: "R&D discussion evidence and contemporaneous documentation",
    category: "r-and-d",
    logoUrl: `${GF}slack.com`,
    connected: false,
    savingsWeight: 2,
  },
  {
    id: "asana",
    name: "Asana",
    description: "Project timelines and task tracking for R&D activities",
    category: "r-and-d",
    logoUrl: `${SI}/asana/F06A6A`,
    connected: false,
    savingsWeight: 2,
  },

  // ── Other (3) ──────────────────────────────────────────
  {
    id: "gmail",
    name: "Gmail",
    description: "Receipt scanning and vendor communications",
    category: "other",
    logoUrl: `${SI}/gmail/EA4335`,
    connected: false,
    savingsWeight: 2,
  },
  {
    id: "google-drive",
    name: "Google Drive",
    description: "Tax documents and financial statements",
    category: "other",
    logoUrl: `${SI}/googledrive/4285F4`,
    connected: false,
    savingsWeight: 2,
  },
  {
    id: "stripe",
    name: "Stripe",
    description: "Payment processing and revenue data",
    category: "other",
    logoUrl: `${SI}/stripe/635BFF`,
    connected: false,
    savingsWeight: 3,
  },
];
